use-permission: true
permission: onlyenchant.use

# сообщения
# если какое-то из сообщений равняется '', оно не будет отправлено
# цвета с & поддерживаются
tip: 'Кликните по предмету, который нужно зачаровать.'
success: 'Вы успешно зачаровали выбранный предмет.'
fail: 'Этот предмет нельзя зачаровать.'
empty: 'Вы вернули зачарование в книгу.'
